default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: hola123
  pool: 5

production:
  <<: *default
  database: tarea1-TI_production

development:
  <<: *default
  database: tarea1-TI_development

test:
  <<: *default
  database: tarea1-TI_test